routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::get('/calender', 'PreviewController@index');
Route::get('/day/{id}', 'PreviewController@show');


Route::group(['middleware'=>'auth'], function(){
Route::resource('day','MonthController');
Route::resource('user','UserController');	
});

app/Month.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Month extends Model
{
    protected $fillable = ['day', 'melady_day','sherouk' , 'emsak', 'fager', 'dohr', 'asr', 'maghreb', 'esha'];
}

app/Slider.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Slider extends Model
{
    protected $fillable = ['image'];
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'username', 'phone_number', 'password', 'image', 'permission',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */

    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use App\Month;
use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $day = Month::get();
        return view('admin.home',compact('day'));
    }
}

app/Http/Controllers/MonthController.php
<?php

namespace App\Http\Controllers;

use App\Month;
use Illuminate\Http\Request;

class MonthController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $day = Month::get();
        return view('admin.home',compact('day'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        if(Month::get()->count() < 30)
        {
            $add=1;
            return view('admin.day',compact('add'));
        }
        else
        {
            return redirect()->back()->with('message','error : ramadan day is completed => 30 day');
        }
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

        if(Month::get()->count() < 30)
        {
            $data = $request->all();
            Month::create($data);
            return redirect()->back()->with('message','successful adding ramadan day');
        }
        else
        {
            return redirect()->back()->with('message','error : ramadan day is completed => 30 day');
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Month  $month
     * @return \Illuminate\Http\Response
     */
    public function show(Month $month)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Month  $month
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $edit = Month::find($id);
        return view('admin.day',compact('edit'));

    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Month  $month
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
         Month::find($id)->update($request->all());
         return redirect()->back()->with('message','successfully updating this day');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Month  $month
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Month::find($id)->delete();
        return redirect()->back()->with('message','successfully deleting this day');
    }
}

app/Http/Controllers/PreviewController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Month;

class PreviewController extends Controller
{
    public function index()
    {
    	$monthes = Month::orderBy('day', 'asc')->get();
    	return view('mainCalender', compact('monthes'));
    }

    public function show($id)
    {
    	$month = Month::find($id);

    	return view('day', compact('month'));
    }
}

app/Http/Controllers/SliderController.php
<?php

namespace App\Http\Controllers;

use App\Slider;
use Illuminate\Http\Request;

class SliderController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Slider  $slider
     * @return \Illuminate\Http\Response
     */
    public function show(Slider $slider)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Slider  $slider
     * @return \Illuminate\Http\Response
     */
    public function edit(Slider $slider)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Slider  $slider
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Slider $slider)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Slider  $slider
     * @return \Illuminate\Http\Response
     */
    public function destroy(Slider $slider)
    {
        //
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/admin/home.blade.php
<!DOCTYPE html>
<html>
    
<!-- Mirrored from coderthemes.com/adminto/bs4/light/calendar.html by HTTrack Website Copier/3.x [XR&CO'2014], Wed, 04 Apr 2018 11:28:57 GMT -->
<head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="description" content="A fully featured admin theme which can be used to build CRM, CMS, etc.">
        <meta name="author" content="Coderthemes">

        <link rel="shortcut icon" href="{{ asset('admin/assets/images/favicon.ico') }}">

        <title>Admin Home Page</title>

        <!--calendar css-->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Lato:300,400,700">
        <!-- App css -->
    <link href="{{ asset('admin/assets/css/bootstrap.min.css') }}" rel="stylesheet" type="text/css" />
    <link href="{{ asset('admin/assets/css/icons.css') }}" rel="stylesheet" type="text/css" />
    <link href="{{ asset('admin/assets/css/style.css') }}" rel="stylesheet" type="text/css" />

    <script src="{{ asset('admin/assets/js/modernizr.min.js') }}"></script>
    <style>
        @charset "utf-8";
        /* CSS Document */

        /* ---------- FONTAWESOME ---------- */
        /* ---------- https://fortawesome.github.com/Font-Awesome/ ---------- */
        /* ---------- http://weloveiconfonts.com/ ---------- */

        @import url(http://weloveiconfonts.com/api/?family=fontawesome);

        *[class*="fontawesome-"]:before {
            font-family: 'FontAwesome', sans-serif;
        }

        /* ---------- GENERAL ---------- */

        body {
            background: #f9f9f9;
            color: #0e171c;
            font: 300 100%/1.5em 'Lato', sans-serif;
            margin: 0;
        }

        a {
            text-decoration: none;
        }

        h2 {
            font-size: 2em;
            line-height: 1.25em;
            margin: .25em 0;
        }

        h3 {
            font-size: 1.5em;
            line-height: 1em;
            margin: .33em 0;
        }

        table {
            border-collapse: collapse;
            border-spacing: 0;
            width: 100%;
        }


        /* ---------- CALENDAR ---------- */

        .calendar {
            text-align: center;
            width: 100%;
        }

        .calendar header {
            position: relative;
        }

        .calendar h2 {
            text-transform: uppercase;
        }

        .calendar thead {
            font-weight: 600;
            text-transform: uppercase;
        }

        .calendar tbody {
            color: #7c8a95;
        }

        .calendar tbody td:hover {
            border: 2px solid #00addf;
        }

        .calendar td {
            border: 2px solid transparent;
            border-radius: 50%;
            display: inline-block;
            height: 4em;
            line-height: 4em;
            text-align: center;
            width: 4em;
        }

        .calendar .prev-month,
        .calendar .next-month {
            color: #cbd1d2;
        }

        .calendar .prev-month:hover,
        .calendar .next-month:hover {
            border: 2px solid #cbd1d2;
        }

        .current-day {
            background: #00addf;
            color: #f9f9f9;
        }

        .event {
            cursor: pointer;
            position: relative;
        }

        .event:after {
            background: #00addf;
            border-radius: 50%;
            bottom: .5em;
            display: block;
            content: '';
            height: .5em;
            left: 50%;
            margin: -.25em 0 0 -.25em;
            position: absolute;
            width: .5em;
        }

        .event.current-day:after {
            background: #f9f9f9;
        }

        .btn-prev,
        .btn-next {
            border: 2px solid #cbd1d2;
            border-radius: 50%;
            color: #cbd1d2;
            height: 2em;
            font-size: .75em;
            line-height: 2em;
            margin: -1em;
            position: absolute;
            top: 50%;
            width: 2em;
        }

        .btn-prev:hover,
        .btn-next:hover {
            background: #cbd1d2;
            color: #f9f9f9;
        }

        .btn-prev {
            left: 6em;
        }

        .btn-next {
            right: 6em;
        }
    </style>
    </head>


    <body class="fixed-left">

        <!-- Begin page -->
        <div id="wrapper">

            <!-- Top Bar Start -->
            @include('admin.template.topMenu')
            <!-- Top Bar End -->


            <!-- ========== Left Sidebar Start ========== -->
            <div class="left side-menu">
                @include('admin.template.leftMenu')

            </div>
            <!-- Left Sidebar End -->



            <!-- ============================================================== -->
            <!-- Start right Content here -->
            <!-- ============================================================== -->
            <div class="content-page">
                <!-- Start content -->
                <div class="content">
                    <div class="container-fluid">
                        <div class="row">
                            <div class="col-lg-12">
                                <div class="calendar">
                                    <header>
                                        <h2>Ramadan 2018</h2>
                                        <h2>{{ date("Y / m / d",time()) }}</h2>
                                    </header>
                                    <table>
                                        <thead>
                                        <tr>
                                            <td>Mo</td>
                                            <td>Tu</td>
                                            <td>We</td>
                                            <td>Th</td>
                                            <td>Fr</td>
                                            <td>Sa</td>
                                            <td>Su</td>
                                        </tr>
                                        </thead>
                                        <tbody>

                                        <tr>
                                            <td></td>
                                            <td></td>
                                            <td></td>
                                            <td><a href="{{ isset($day[0]->day)?  url('day/'.$day[0]->id.'/edit') : '' }}">{{ isset($day[0]->day)? $day[0]->day : '' }}</a></td>
                                            <td><a href="{{ isset($day[1]->day)?  url('day/'.$day[1]->id.'/edit') : '' }}">{{ isset($day[1]->day)? $day[1]->day : '' }}</a></td>
                                            <td><a href="{{ isset($day[2]->day)?  url('day/'.$day[2]->id.'/edit') : '' }}">{{ isset($day[2]->day)? $day[2]->day : '' }}</a></td>
                                            <td><a href="{{ isset($day[3]->day)?  url('day/'.$day[3]->id.'/edit') : '' }}">{{ isset($day[3]->day)? $day[3]->day : '' }}</a></td>
                                        </tr>
                                        <tr>
                                            <td><a href="{{ isset($day[4]->day)?  url('day/'.$day[4]->id.'/edit') : '' }}">{{ isset($day[4]->day)? $day[4]->day : '' }}</a></td>
                                            <td><a href="{{ isset($day[5]->day)?  url('day/'.$day[5]->id.'/edit') : '' }}">{{ isset($day[3]->day)? $day[5]->day : '' }}</a></td>
                                            <td><a href="{{ isset($day[6]->day)?  url('day/'.$day[6]->id.'/edit') : '' }}">{{ isset($day[3]->day)? $day[6]->day : '' }}</a></td>
                                            <td><a href="{{ isset($day[7]->day)?  url('day/'.$day[7]->id.'/edit') : '' }}">{{ isset($day[3]->day)? $day[3]->day : '' }}</a></td>
                                            <td><a href="{{ isset($day[8]->day)?  url('day/'.$day[8]->id.'/edit') : '' }}">{{ isset($day[3]->day)? $day[3]->day : '' }}</a></td>
                                            <td><a href="{{ isset($day[9]->day)?  url('day/'.$day[9]->id.'/edit') : '' }}">{{ isset($day[3]->day)? $day[3]->day : '' }}</a></td>
                                            <td><a href="{{ isset($day[10]->day)?  url('day/'.$day[10]->id.'/edit') : '' }}">{{ isset($day[3]->day)? $day[3]->day : '' }}</a></td>
                                        </tr>
                                        <tr>
                                            <td><a href="{{ url('day/'.$day[11]->id.'/edit') }}">{{ $day[11]->day }}</a></td>
                                            <td><a href="{{ url('day/'.$day[12]->id.'/edit') }}">{{ $day[12]->day }}</a></td>
                                            <td><a href="{{ url('day/'.$day[13]->id.'/edit') }}">{{ $day[13]->day }}</a></td>
                                            <td><a href="{{ url('day/'.$day[14]->id.'/edit') }}">{{ $day[14]->day }}</a></td>
                                            <td><a href="{{ url('day/'.$day[15]->id.'/edit') }}">{{ $day[15]->day }}</a></td>
                                            <td><a href="{{ url('day/'.$day[16]->id.'/edit') }}">{{ $day[16]->day }}</a></td>
                                            <td><a href="{{ url('day/'.$day[17]->id.'/edit') }}">{{ $day[17]->day }}</a></td>
                                        </tr>
                                        <tr>
                                            <td><a href="{{ url('day/'.$day[18]->id.'/edit') }}">{{ $day[18]->day }}</a></td>
                                            <td><a href="{{ url('day/'.$day[19]->id.'/edit') }}">{{ $day[19]->day }}</a></td>
                                            <td><a href="{{ url('day/'.$day[20]->id.'/edit') }}">{{ $day[20]->day }}</a></td>
                                            <td><a href="{{ url('day/'.$day[21]->id.'/edit') }}">{{ $day[21]->day }}</a></td>
                                            <td><a href="{{ url('day/'.$day[22]->id.'/edit') }}">{{ $day[22]->day }}</a></td>
                                            <td><a href="{{ url('day/'.$day[23]->id.'/edit') }}">{{ $day[23]->day }}</a></td>
                                            <td><a href="{{ url('day/'.$day[24]->id.'/edit') }}">{{ $day[24]->day }}</a></td>
                                        </tr>
                                        <tr>
                                            <td><a href="{{ url('day/'.$day[25]->id.'/edit') }}">{{ $day[25]->day }}</a></td>
                                            <td><a href="{{ url('day/'.$day[26]->id.'/edit') }}">{{ $day[26]->day }}</a></td>
                                            <td><a href="{{ url('day/'.$day[27]->id.'/edit') }}">{{ $day[27]->day }}</a></td>
                                            <td><a href="{{ url('day/'.$day[28]->id.'/edit') }}">{{ $day[28]->day }}</a></td>
                                            <td><a href="{{ url('day/'.$day[29]->id.'/edit') }}">{{ $day[29]->day }}</a></td><td></td>
                                            <td></td>
                                        </tr>
                                        </tbody>
                                    </table>
                                    </div>
                            </div>
                            <!-- end col-12 -->
                        </div> <!-- end row -->

                    </div> <!-- container -->

                </div> <!-- content -->

                <footer class="footer text-right">
                    2016 - 2018 © Adminto. Coderthemes.com
                </footer>

            </div>


            <!-- ============================================================== -->
            <!-- End Right content here -->
            <!-- ============================================================== -->


            <!-- Right Sidebar -->
            <!-- /Right-bar -->

        </div>
        <!-- END wrapper -->


        <!-- jQuery  -->
        <script src="{{ asset('admin/assets/js/jquery.min.js') }}"></script>
        <script src="{{ asset('admin/assets/js/popper.min.js') }}"></script>
        <script src="{{ asset('admin/assets/js/bootstrap.min.js') }}"></script>
        <script src="{{ asset('admin/assets/js/detect.js') }}"></script>
        <script src="{{ asset('admin/assets/js/fastclick.js') }}"></script>
        <script src="{{ asset('admin/assets/js/jquery.blockUI.js') }}"></script>
        <script src="{{ asset('admin/assets/js/waves.js') }}"></script>
        <script src="{{ asset('admin/assets/js/jquery.nicescroll.js') }}"></script>
        <script src="{{ asset('admin/assets/js/jquery.slimscroll.js') }}"></script>
        <script src="{{ asset('admin/assets/js/jquery.scrollTo.min.js') }}"></script>

        <!-- App js -->
        <script src="{{ asset('admin/assets/js/jquery.core.js') }}"></script>
        <script src="{{ asset('admin/assets/js/jquery.app.js') }}"></script>

        <!-- Jquery-Ui -->
        <script src="{{ asset('admin/assets/plugins/jquery-ui/jquery-ui.min.js') }}"></script>

        <!-- SCRIPTS -->


    </body>
</html>

resources/views/admin/login.blade.php
<!DOCTYPE html>
<html>
    
<!-- Mirrored from coderthemes.com/adminto/bs4/light/page-login.html by HTTrack Website Copier/3.x [XR&CO'2014], Wed, 04 Apr 2018 11:28:59 GMT -->
<head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="description" content="A fully featured admin theme which can be used to build CRM, CMS, etc.">
        <meta name="author" content="Coderthemes">

        <link rel="shortcut icon" href="{{ asset('admin/assets/images/favicon.ico') }}">

        <title>Adminto - Responsive Admin Dashboard Template</title>

        <!-- App css -->
        <link href="{{ asset('admin/assets/css/bootstrap.min.css') }}" rel="stylesheet" type="text/css" />
        <link href="{{ asset('admin/assets/css/icons.css') }}" rel="stylesheet" type="text/css" />
        <link href="{{ asset('admin/assets/css/style.css') }}" rel="stylesheet" type="text/css" />

        <script src="{{ asset('admin/assets/js/modernizr.min.js') }}"></script>

    </head>

    <body>

        <div class="account-pages"></div>
        <div class="clearfix"></div>
        <div class="wrapper-page">
            <div class="text-center">
                <a href="{{ url('/') }}" class="logo"><span>Welcome Back <span>Admin</span></span></a>
                <h5 class="text-muted m-t-0 font-600">Please Login To Continue</h5>
            </div>
        	<div class="m-t-40 card-box">
                <div class="text-center">
                    <h4 class="text-uppercase font-bold m-b-0">Sign In</h4>
                </div>
                <div class="p-20">
                    <form class="form-horizontal m-t-20" method="POST" action="{{ route('login') }}">
                        @csrf
                        <div class="form-group">
                            <div class="col-xs-12">
                                <input id="email" type="email" class="form-control{{ $errors->has('email') ? ' is-invalid' : '' }}" name="email" value="{{ old('email') }}" required autofocus>
                            </div>
                        </div>
                        @if ($errors->has('email'))
                            <span class="invalid-feedback">
                                  <strong>{{ $errors->first('email') }}</strong>
                            </span>
                        @endif
                        <div class="form-group">
                            <div class="col-xs-12">
                                <input id="password" type="password" class="form-control{{ $errors->has('password') ? ' is-invalid' : '' }}" name="password" required>
                            </div>
                        </div>
                        @if ($errors->has('password'))
                            <span class="invalid-feedback">
                                  <strong>{{ $errors->first('password') }}</strong>
                            </span>
                        @endif
                        <div class="form-group text-center m-t-30">
                            <div class="col-xs-12">
                                <button class="btn btn-custom btn-bordred btn-block waves-effect waves-light" type="submit">Log In</button>
                            </div>
                        </div>
                    </form>

                </div>
            </div>
            <!-- end card-box-->

            <div class="row">
                <div class="col-sm-12 text-center">
                    <p class="text-muted">Don't have an account? <a href="page-register.html" class="text-primary m-l-5"><b>Sign Up</b></a></p>
                </div>
            </div>
            
        </div>
        <!-- end wrapper page -->



        <!-- jQuery  -->
        <script src="{{ asset('admin/assets/js/modernizr.min.js') }}"></script>
        <script src="{{ asset('admin/asset/js/popper.min.js') }}"></script>
        <script src="{{ asset('admin/asset/js/bootstrap.min.js') }}"></script>
        <script src="{{ asset('admin/asset/js/detect.js') }}"></script>
        <script src="{{ asset('admin/asset/js/fastclick.js') }}"></script>
        <script src="{{ asset('admin/asset/js/jquery.blockUI.js') }}"></script>
        <script src="{{ asset('admin/asset/js/waves.js') }}assets/js/"></script>
        <script src="{{ asset('admin/asset/js/jquery.nicescroll.js') }}"></script>
        <script src="{{ asset('admin/asset/js/jquery.slimscroll.js') }}"></script>
        <script src="{{ asset('admin/asset/js/jquery.scrollTo.min.js') }}"></script>

        <!-- App js -->
        <script src="{{ asset('admin/asset/js/jquery.core.js') }}"></script>
        <script src="{{ asset('admin/asset/js/jquery.app.js') }}"></script>
	
	</body>

<!-- Mirrored from coderthemes.com/adminto/bs4/light/page-login.html by HTTrack Website Copier/3.x [XR&CO'2014], Wed, 04 Apr 2018 11:28:59 GMT -->
</html>

resources/views/admin/template/leftMenu.blade.php
<div class="sidebar-inner slimscrollleft">

    <!-- UserController -->
    <div class="user-box">
        <div class="user-img">
            <img src="{{ asset('admin/assets/images/users/avatar-1.jpg') }}" alt="user-img" title="Mat Helme" class="rounded-circle img-thumbnail img-responsive">
            <div class="user-status offline"><i class="mdi mdi-adjust"></i></div>
        </div>
        <h5><a>{{ auth()->user()->name }}</a> </h5>
        <ul class="list-inline">
            <li class="list-inline-item">
                <a href="#" >
                    <i class="mdi mdi-settings"></i>
                </a>
            </li>

            <li class="list-inline-item">
                <form action="logout" method="POST">
                    @csrf
                    <button class="text-custom">
                        <i class="mdi mdi-power"></i>
                    </button>
                </form>
            </li>
        </ul>
    </div>
    <!-- End UserController -->

    <!--- Sidemenu -->
    <div id="sidebar-menu">
        <ul>
            <li class="text-muted menu-title">Navigation</li>

            <li>
                <a href="{{ url('home') }}" class="waves-effect"><i class="mdi mdi-view-dashboard"></i> <span> Dashboard </span> </a>
            </li>

            <li class="has_sub">
                <a href="javascript:void(0);" class="waves-effect"><i class="mdi mdi-format-font"></i><span> Day </span> </a>
                <ul class="list-unstyled">
                    <li><a href="{{ route('day.create') }}">Add day</a></li>
                    <li><a href="{{ route('day.index') }}">Show Days</a></li>
                </ul>
            </li>

            <li class="has_sub">
                <a href="javascript:void(0);" class="waves-effect"><i class="mdi mdi-view-list"></i> <span> Admin </span></a>
                <ul class="list-unstyled">
                    <li><a href="{{ route('user.create') }}">Add Admin</a></li>
                    <li><a href="{{ route('user.index') }}">Show Admins</a></li>
                </ul>
            </li>
        </ul>
        <div class="clearfix"></div>
    </div>
    <!-- Sidebar -->
    <div class="clearfix"></div>

</div>

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
<div class="card">
    <div class="card-header">Dashboard</div>

    <div class="card-body">
        @if (session('status'))
            <div class="alert alert-success">
                {{ session('status') }}
            </div>
        @endif

        You are logged in!
    </div>
</div>
</div>
</div>
</div>
@endsection